# Generated by Django 2.0.3 on 2018-03-31 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('quantity_Checked_Out', models.IntegerField(default=0)),
                ('id_Number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('MEMBER', 'MEMBER'), ('ADMIN', 'ADMIN'), ('MEMBER_EXPIRED', 'MEMBER EXPIRED'), ('NON_MEMBER', 'NON MEMBER'), ('OFFICER', 'OFFICER')], default='MEMBER', max_length=20)),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('cal_Poly_Email', models.EmailField(max_length=100)),
                ('ieee_member_number', models.CharField(max_length=100, null=True)),
                ('ieee_member_expiration_date', models.DateField(null=True)),
                ('phone_Number', models.IntegerField(default=0, null=True)),
                ('polyCard_Data', models.CharField(max_length=100, null=True)),
                ('has_Items_Checked_Out', models.BooleanField(default=False)),
                ('parts', models.ManyToManyField(null=True, to='app_Transaction.Part')),
            ],
        ),
        migrations.CreateModel(
            name='userPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=100)),
                ('quantity_Checked_Out', models.IntegerField(default=0)),
                ('id_Number', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('userAssigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userAssigned', to='app_Transaction.User')),
            ],
        ),
    ]
