# Generated by Django 2.0.3 on 2018-03-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0002_auto_20180331_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parts',
            field=models.ManyToManyField(blank=True, to='app_Transaction.Part'),
        ),
    ]
