# Generated by Django 2.0.3 on 2018-03-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0003_auto_20180331_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_Number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
