# Generated by Django 2.0 on 2017-12-19 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0003_auto_20171219_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='week_Number',
            new_name='experiment_Number',
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 19, 14, 8, 36, 242474)),
        ),
    ]
