# Generated by Django 2.0.3 on 2018-03-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0004_auto_20180331_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cal_Poly_Email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_Name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='ieee_member_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_Name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='polyCard_Data',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('MEMBER', 'MEMBER'), ('ADMIN', 'ADMIN'), ('MEMBER_EXPIRED', 'MEMBER EXPIRED'), ('NON_MEMBER', 'NON MEMBER'), ('OFFICER', 'OFFICER')], default=('MEMBER', 'MEMBER'), max_length=20),
        ),
    ]
