# Generated by Django 2.0 on 2017-12-20 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0004_auto_20171219_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolyCard',
        ),
        migrations.AddField(
            model_name='user',
            name='iso_Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='library_Code_Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 19, 17, 1, 20, 308958)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Cal Poly Email'),
        ),
    ]
