# Generated by Django 2.0.3 on 2018-03-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0005_auto_20180331_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('MEMBER', 'MEMBER'), ('ADMIN', 'ADMIN'), ('MEMBER_EXPIRED', 'MEMBER EXPIRED'), ('NON_MEMBER', 'NON MEMBER'), ('OFFICER', 'OFFICER')], default=('MEMBER', 'MEMBER'), max_length=50),
        ),
    ]
