# Generated by Django 2.0 on 2017-12-20 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0005_auto_20171219_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='polyCard_Data_Text',
            field=models.CharField(default='PolyCard Data', max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 19, 17, 8, 1, 9128)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_Name_Text',
            field=models.CharField(default='First name', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_Name_Text',
            field=models.CharField(default='Last name', max_length=100),
        ),
    ]
