# Generated by Django 2.0 on 2017-12-20 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0006_auto_20171219_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 19, 17, 12, 3, 489465)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_Name_Text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_Name_Text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='polyCard_Data_Text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
