# Generated by Django 2.0 on 2017-12-20 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0007_auto_20171219_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_Items_Checked_Out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 19, 22, 47, 25, 123747)),
        ),
    ]
