# Generated by Django 2.0 on 2017-12-25 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0008_auto_20171219_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_phone_Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 24, 23, 41, 8, 59579)),
        ),
    ]
