# Generated by Django 2.0 on 2017-12-25 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0009_auto_20171224_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_phone_Number',
            new_name='user_Phone_Number',
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 25, 15, 54, 47, 301888)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Type_Text',
            field=models.CharField(default='STUDENT', max_length=100),
        ),
    ]
