# Generated by Django 2.0 on 2017-12-26 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0010_auto_20171225_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 25, 16, 6, 49, 995437)),
        ),
    ]
