# Generated by Django 2.0 on 2017-12-26 00:07

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0011_auto_20171225_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 25, 16, 7, 59, 696210)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Phone_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
