# Generated by Django 2.0 on 2017-12-26 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0012_auto_20171225_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 25, 16, 19, 27, 223787)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Phone_Number',
            field=models.IntegerField(default=0),
        ),
    ]
