# Generated by Django 2.0 on 2017-12-26 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0013_auto_20171225_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_Name_Text',
            new_name='first_Name',
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 25, 16, 28, 41, 9260)),
        ),
    ]
