# Generated by Django 2.0 on 2017-12-26 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0015_auto_20171225_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='polyCard_Data_Text',
            new_name='polyCard_Data',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_Type_Text',
            new_name='user_Type',
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 25, 18, 32, 7, 491285)),
        ),
    ]
