# Generated by Django 2.0 on 2017-12-27 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0016_auto_20171225_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parts',
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 27, 13, 54, 1, 402200)),
        ),
    ]
