# Generated by Django 2.0 on 2017-12-28 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0017_auto_20171227_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_Name_Text',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='quantity_Checked_Out_Number',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='quantity_Number',
            new_name='quantity_Checked_Out',
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 27, 20, 16, 58, 191109)),
        ),
    ]
