# Generated by Django 2.1 on 2017-12-28 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0018_auto_20171227_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 27, 21, 37, 50, 706175)),
        ),
    ]
