# Generated by Django 2.1 on 2017-12-28 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0019_auto_20171227_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 27, 21, 41, 18, 901630)),
        ),
    ]
