# Generated by Django 2.1 on 2017-12-28 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0021_auto_20171227_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 28, 12, 18, 37, 286756)),
        ),
    ]
