# Generated by Django 2.1 on 2017-12-29 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0023_auto_20171228_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parts',
            field=models.ManyToManyField(to='app_Transaction.Part'),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 29, 9, 39, 48, 960933)),
        ),
    ]
