# Generated by Django 2.0.1 on 2018-01-10 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0025_auto_20171229_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='userPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAssigned', models.EmailField(max_length=100, null=True)),
                ('part', models.CharField(max_length=100)),
                ('quantity_Checked_Out', models.IntegerField(default=0)),
                ('id_Number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 9, 17, 24, 19, 471197)),
        ),
    ]
