# Generated by Django 2.0.1 on 2018-01-10 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0026_auto_20180109_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parts',
        ),
        migrations.AlterField(
            model_name='log',
            name='date_And_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 9, 17, 25, 29, 349301)),
        ),
    ]
