# Generated by Django 2.0.1 on 2018-01-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0027_auto_20180109_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date_And_Time',
        ),
        migrations.AlterField(
            model_name='userpart',
            name='id_Number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
