# Generated by Django 2.0.1 on 2018-01-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0028_auto_20180111_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpart',
            name='userAssigned',
        ),
    ]
