# Generated by Django 2.0.1 on 2018-01-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0030_userpart_userassigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpart',
            name='id_Number',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
