# Generated by Django 2.0.1 on 2018-01-13 20:50

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0031_auto_20180113_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logType', models.TextField()),
                ('content', jsonfield.fields.JSONField()),
                ('checkedOutBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkedOutBy', to='app_Transaction.User')),
                ('checkedOutTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkedOutTo', to='app_Transaction.User')),
            ],
        ),
    ]
