# Generated by Django 2.0.1 on 2018-01-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0032_eventlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpart',
            name='userAssigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userAssigned', to='app_Transaction.User'),
        ),
    ]
