# Generated by Django 2.0.1 on 2018-01-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0035_auto_20180113_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='parts',
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='logType',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userpart',
            name='id_Number',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
