# Generated by Django 2.0.2 on 2018-03-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0036_auto_20180113_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='iso_Number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='library_Code_Number',
        ),
        migrations.AddField(
            model_name='user',
            name='ieee_member_expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ieee_member_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parts',
            field=models.ManyToManyField(to='app_Transaction.Part'),
        ),
    ]
