# Generated by Django 2.0.2 on 2018-03-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0037_auto_20180304_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MEMBER', 'MEMBER'), ('MEMBER_EXPIRED', 'MEMBER_EXPIRED'), ('NON_MEMBER', 'NON_MEMBER'), ('OFFICER', 'OFFICER')], default='MEMBER', max_length=20),
        ),
    ]
