# Generated by Django 2.0.3 on 2018-03-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transaction', '0038_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_Type',
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MEMBER', 'MEMBER'), ('MEMBER_EXPIRED', 'MEMBER EXPIRED'), ('NON_MEMBER', 'NON MEMBER'), ('OFFICER', 'OFFICER')], default='MEMBER', max_length=20),
        ),
    ]
